#!/bin/sh
# Install the .so into its appropriate location

case "$1" in
    freebsd*)
    echo "FreeBSD: Installing pam_sqlite3.so to $ROOTDIR/usr/lib"
    destdir=usr/lib
    ;;
    linux*)
    echo "Linux: Installing pam_sqlite3.so to $ROOTDIR/lib/security"
    destdir=lib/security
    ;;
    *)
    echo "Unknown: Installing pam_sqlite3.so to $ROOTDIR/lib/security"
    destdir=lib/security
    ;;
esac

install -c -m 755 -o root pam_sqlite3.so $ROOTDIR/$destdir
