#!/bin/sh
# Install the .so into its appropriate location

case "$1" in
    freebsd*)
    echo "FreeBSD: Installing pam_sqlite3.so to $ROOTDIR/usr/lib"
    destdir=usr/lib
    ;;
    linux*)
    if [ -d "$ROOTDIR/lib/$(uname -m)-${1}" ]; then
        echo "Linux: Installing pam_sqlite3.so to $ROOTDIR/lib/$(uname -m)-${1}/security"
        destdir=lib/$(uname -m)-${1}/security
    else
        echo "Linux: Installing pam_sqlite3.so to $ROOTDIR/lib/security"
        destdir=lib/security
    fi
    ;;
    *)
    echo "Unknown: Installing pam_sqlite3.so to $ROOTDIR/lib/security"
    destdir=lib/security
    ;;
esac

if [ `id -u` -eq 0 ]; then
    install -c -m 755 -o root pam_sqlite3.so $ROOTDIR/$destdir
else
    install -c -m 0755 pam_sqlite3.so $ROOTDIR/$destdir
fi
